# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0
group=tfar
java_version=21

# Common
minecraft_version=1.21.1
mod_name=AE2Extras
mod_author=Jared
mod_id=ae2extras
license=CC0-1.0
credits=
description=The description of your mod. \\nAccepts multilines (but they must be double-escaped).
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
# check these on https://fabricmc.net/develop
fabric_version=0.104.0+1.21.1
fabric_loader_version=0.16.3

# NeoForge
neoforge_version=21.1.197
neoforge_loader_version_range=[4,)

#Other mods
use_rei=false
rei_version=16.0.729
cloth_config_version=15.0.127
architectury_version=13.0.6

ae2_version=19.2.17
jei_version=19.27.0.340
guideme_version=21.1.15
guideme_version_range=[21.1.1,21.2.0)
mekanism_version=1.21.1-10.7.18.84

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false